pipeline:
  type: chain
  transforms:
    # Step 1: Reading data from Iceberg
    - type: ReadFromIceberg
      name: ReadFromIcebergTable
      config:
        table: "db.users.NY"
        catalog_name: "hadoop_catalog"
        catalog_properties:
          type: "hadoop"
          warehouse: "gs://apache-beam-samples/iceberg-examples"
        config_properties:
          "fs.gs.auth.type": "SERVICE_ACCOUNT_JSON_KEYFILE"
          "fs.gs.auth.service.account.json.keyfile": "/Users/tannapareddy/Desktop/apache-beam-testing-7826284c1ea3.json"

    # Step 2: Write records out to AlloyDB
    - type: WriteToJdbc
      name: WriteToAlloyDBTable
      config:
        location: "users"
        driver_class_name: "org.postgresql.Driver"
        jdbc_url: "jdbc:postgresql:///db?socketFactory=com.google.cloud.alloydb.SocketFactory&alloydbInstanceName=projects/apache-beam-testing/locations/us-central1/clusters/alloydb-yaml-test/instances/alloydb-yaml-test-primary&alloydbIpType=PUBLIC"
        username: "postgres"
        password: ',Ne]$?(\l`@CS8fM'
